name: ExcellentPlugins

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/ExcellentPlugins.yml'
  schedule:
    - cron: '0 0 */3 * *'

jobs: 
  ExcellentJobs-spigot:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "nulli0n/ExcellentJobs-spigot"
      name: "ExcellentJobs-spigot"
      java: 17
   ExcellentShop-spigot:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "nulli0n/ExcellentShop-spigot"
      name: "ExcellentShop-spigot"
      java: 17
 
   AdvancedMobArena-spigot:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "nulli0n/AdvancedMobArena-spigot"
      name: "AdvancedMobArena-spigot"
      java: 17
 
   ExcellentChallenges-spigot:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "nulli0n/ExcellentChallenges-spigot"
      name: "ExcellentChallenges-spigot"
      java: 17
 
   CombatPets-spigot:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "nulli0n/CombatPets-spigot"
      name: "CombatPets-spigot"
      java: 17
 
   LootConomy-spigot:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "nulli0n/LootConomy-spigot"
      name: "LootConomy-spigot"
      java: 17
