name: Folia
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'PaperMC/Folia'
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Apply Patches
      run: ./gradlew applyPatches
    - name: createReobfBundlerJar
      run: ./gradlew createReobfBundlerJar
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Folia-build
        path: build/libs
    - name: Send Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.https://discord.com/api/webhooks/1282569332689338398/M3JXIw-E1p_KNaPYorlMXGW7x_jxuiF9weOt9vVJfBULPXann_J8HK79c7QmVdTtDHK- }}
        status: ${{ job.status }}
        title: "Folia Build"
        description: "Build completed"
        color: 0x0000ff
        username: GitHub Actions
        avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
    - name: Upload to Discord
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.https://discord.com/api/webhooks/1282569332689338398/M3JXIw-E1p_KNaPYorlMXGW7x_jxuiF9weOt9vVJfBULPXann_J8HK79c7QmVdTtDHK- }}
      with:
        args: build/libs/*.jar
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'PaperMC/Folia'
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
