name: Folia MC
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/Folia.yml'
  schedule:
    - cron: '0 */12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'PaperMC/Folia'
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Configure Git
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "GitHub Actions"
    - name: Apply Patches
      run: ./gradlew applyPatches
    - name: createReobfBundlerJar
      run: ./gradlew createReobfBundlerJar
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Folia-build
        path: build/libs
    - name: Get artifact name
      id: get_artifact
      run: |
        FILE_NAME=$(ls build/libs/*.jar | head -n 1)
        echo "file_name=$(basename $FILE_NAME)" >> $GITHUB_OUTPUT
      shell: bash
    - name: Send to Discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK1 }}
      run: |
        if [ -z "${{ steps.get_artifact.outputs.file_name }}" ]; then
          echo "No artifact found. Sending error message to Discord."
          curl -H "Content-Type: application/json" \
               -d '{"content":"Error: No Folia jar was created in the build."}' \
               $DISCORD_WEBHOOK
        else
          echo "Sending artifact to Discord: ${{ steps.get_artifact.outputs.file_name }}"
          curl -H "Content-Type: multipart/form-data" \
               -F "file=@build/libs/${{ steps.get_artifact.outputs.file_name }}" \
               -F "content=New build of Folia is available!" \
               $DISCORD_WEBHOOK
        fi
      shell: bash
    - name: Send Discord Notification
      uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK1 }}
        status: ${{ job.status }}
        title: "Folia Build"
        description: "Build completed"
        color: 0x0000ff
        username: GitHub Actions
        avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        repository: 'PaperMC/Folia'
        fetch-depth: 0
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
