name: Skript

on:
  push:
    branches:
      - 'feature/folia'
    tags-ignore:
      - '**'
jobs:
  skript:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "SkriptLang/Skript"
      target: "bin/*"
      name: "skript"
      java: 21
      readonly: true
