name: RedLimiterReloaded-Folia
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/RedLimiterReloaded-Folia.yml'
  schedule:
    - cron: '0 */12 * * *'
jobs:
  RedLimiterReloaded-Folia:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Folia-Inquisitors/RedLimiterReloaded-Folia"
      name: "RedLimiterReloaded-Folia"
      target: "target/*"
      java: 17

