name: zKoth
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/zKoth.yml'
  schedule:
    - cron: '0 */12 * * *'
jobs:
  zKoth:
    uses: HSGamer/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Maxlego08/zKoth"
      name: "zKoth"
      target: "target/*"
      java: 17

  discord_webhook:
    needs: zKoth
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: PlayerVaults
          path: ./artifact

      - name: List files
        run: ls -R ./artifact

      - name: Get artifact name
        id: get_artifact
        run: |
          FILE_NAME=$(ls ./artifact | head -n 1)
          echo "file_name=$FILE_NAME" >> $GITHUB_OUTPUT
        shell: bash

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK2 }}
        run: |
          if [ -z "${{ steps.get_artifact.outputs.file_name }}" ]; then
            echo "No artifact found. Sending error message to Discord."
            curl -H "Content-Type: application/json" \
                 -d '{"content":"Error: No artifact was created in the PlayerVaults build."}' \
                 $DISCORD_WEBHOOK
          else
            echo "Sending artifact to Discord: ${{ steps.get_artifact.outputs.file_name }}"
            curl -H "Content-Type: multipart/form-data" \
                 -F "file=@./artifact/${{ steps.get_artifact.outputs.file_name }}" \
                 -F "content=# Bản cập nhật mới zKoth #!" \
                 $DISCORD_WEBHOOK
          fi
        shell: bash
