name: zPlugins

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/zPlugins.yml'
  schedule:
    - cron: '0 */12 * * *'

jobs:
  zEssentials:
    uses: HSGamer/ConstructProjects/.github/workflows/gradle-build.yml@main
    with:
      repository: "Maxlego08/zEssentials"
      name: "zEssentials"
      java: 17
      target: "target/*"
  zKoth:
    uses: Dungjava/ConstructProjects/.github/workflows/maven-build.yml@main
    with:
      repository: "Maxlego08/zKoth"
      name: "zKoth"
      java: 17
